export {
  formatDashboardDate,
  formatDashboardDateTime,
  formatDashboardDateWithWeekday,
  formatDashboardRelativeTime,
} from './format-date';
export { dashboardNavItems, dashboardPageMeta, getDashboardPageMeta, type DashboardNavItem } from './nav.config';
export {
  widgetDemoStates,
  continueLearningPlaceholder,
  learningProgressPlaceholder,
  recentActivityPlaceholder,
  quickActionsPlaceholder,
  notificationPlaceholders,
  type WidgetViewState,
} from './placeholder-data';
export {
  learningViewState,
  learningPageCopy,
  statusFilterOptions,
  sortOptions,
  statusBadgeLabel,
  difficultyBadgeLabel,
  enrolledCourses,
  learningStats,
  continueLearningItem,
  recentlyAccessedItems,
  filterEnrolledCourses,
  sortEnrolledCourses,
  formatLastAccessedLabel,
  type CourseStatus,
  type CourseDifficulty,
  type LearningViewState,
  type CourseStatusFilter,
  type CourseSortOption,
  type InstructorSummaryDto,
  type EnrolledCourseDto,
  type LearningStatDto,
  type ContinueLearningDto,
  type RecentlyAccessedDto,
} from './mock-learning';
export {
  courseDetailsCatalog,
  courseDetailsById,
  courseDetailsCopy,
  courseDetailsViewState,
  courseTabItems,
  difficultyLabel,
  formatAnnouncementDate,
  getCourseDetailsById,
  lessonStatusLabel,
  lessonTypeLabel,
  listCourseDetailIds,
  type CertificateAvailability,
  type CourseAnnouncementDto,
  type CourseCertificateDto,
  type CourseDetailsDto,
  type CourseDetailsViewState,
  type CourseFeaturesDto,
  type CourseLessonDto,
  type CourseMediaDto,
  type CourseMetaDto,
  type CourseModuleDto,
  type CourseProgressDto,
  type CourseResourceDto,
  type CourseTabId,
  type InstructorDto,
  type LessonProgressStatus,
  type LessonType,
  type ResourceType,
} from './mock-course-details';
export {
  lessonPlayerViewState,
  lessonPlayerCopy,
  lessonTypeLabel as playerLessonTypeLabel,
  lessonResourceKindLabel,
  lessonStatusLabel as playerLessonStatusLabel,
  lessonCourseCatalog,
  getLessonCourseTree,
  getLessonPlayerData,
  getDefaultLessonId,
  listLessonIdsForCourse,
  completionStatusLabel,
  type LessonPlayerViewState,
  type LessonContentType,
  type LessonResourceKind,
  type ReadingBlockType,
  type ProgressPercentDto,
  type LessonDurationDto,
  type LessonResourceDto,
  type LessonNotesDto,
  type LessonNavigationDto,
  type VideoContentDto,
  type ReadingBlockDto,
  type ReadingContentDto,
  type PdfContentDto,
  type ExerciseContentDto,
  type UnknownContentDto,
  type LessonContentDto,
  type LessonFeaturesDto,
  type LessonOutlineDto,
  type ModuleOutlineDto,
  type LessonDetailDto,
  type LessonPlayerCourseDto,
  type LessonPlayerModuleDto,
  type LessonPlayerDto,
} from './mock-lessons';
export {
  liveViewState,
  livePageCopy,
  liveStatusLabel,
  meetingPlatformLabel,
  liveClasses,
  getTodaysLiveClass,
  getUpcomingLiveClasses,
  getFeaturedLiveClass,
  getLiveClassDateKeys,
  toLocalDateKey,
  formatLiveDate,
  formatLiveTime,
  formatLiveTimeRange,
  type LiveClassViewState,
  type LiveClassStatus,
  type MeetingPlatform,
  type LiveCourseRefDto,
  type LiveMentorDto,
  type LiveDurationDto,
  type LiveThumbnailDto,
  type LiveMeetingDetailsDto,
  type LiveFutureFeaturesDto,
  type LiveClassDto,
} from './mock-live';
export {
  assignmentsViewState,
  assignmentsPageCopy,
  assignmentStatusLabel,
  assignmentPriorityLabel,
  assignmentSubmissionStatusLabel,
  assignmentStatusFilterOptions,
  assignmentSortOptions,
  assignments,
  getAssignmentStats,
  getUpcomingDeadline,
  filterAssignments,
  sortAssignments,
  formatAssignmentDate,
  getAssignmentById,
  type AssignmentsViewState,
  type AssignmentStatus,
  type AssignmentPriority,
  type AssignmentSubmissionStatus,
  type AssignmentSortOption,
  type AssignmentStatusFilter,
  type AssignmentMentorDto,
  type AssignmentDurationDto,
  type AssignmentAttachmentDto,
  type AssignmentFeedbackDto,
  type AssignmentMarksDto,
  type AssignmentProgressDto,
  type AssignmentFutureFeaturesDto,
  type AssignmentDto,
  type AssignmentStatDto,
} from './mock-assignments';
export {
  certificatesViewState,
  certificatesPageCopy,
  certificateStatusLabel,
  certificateStatusFilterOptions,
  certificateSortOptions,
  certificates,
  getCertificateStats,
  filterCertificates,
  sortCertificates,
  formatCertificateDate,
  getCertificateById,
  type CertificatesViewState,
  type CertificateStatus,
  type CertificateStatusFilter,
  type CertificateSortOption,
  type CertificateMentorDto,
  type CertificateFutureFeaturesDto,
  type CertificateTimelineStepDto,
  type CertificateDto,
  type CertificateStatDto,
} from './mock-certificates';
export {
  profileViewState,
  settingsViewState,
  profilePageCopy,
  settingsPageCopy,
  accountStatusLabel,
  themePreferenceLabel,
  studentProfile,
  getStudentDisplayName,
  formatProfileDate,
  getLanguageLabel,
  type ProfileViewState,
  type SettingsViewState,
  type AccountStatus,
  type ThemePreference,
  type ProfileOrganizationDto,
  type ProfileAcademicDto,
  type NotificationPreferencesDto,
  type PrivacyPreferencesDto,
  type ConnectedAccountDto,
  type StudentPreferencesDto,
  type ProfileFutureFeaturesDto,
  type StudentProfileDto,
} from './mock-profile';
export {
  notificationsViewState,
  notificationsPageCopy,
  notificationTypeLabel,
  notificationPriorityLabel,
  notificationStatusFilterOptions,
  notificationSortOptions,
  notifications,
  getNotificationStats,
  filterNotifications,
  sortNotifications,
  formatNotificationDate,
  formatNotificationRelativeTime,
  getNotificationById,
  isNotificationUnread,
  type NotificationsViewState,
  type NotificationType,
  type NotificationPriority,
  type NotificationStatusFilter,
  type NotificationSortOption,
  type NotificationFutureFeaturesDto,
  type NotificationDto,
  type NotificationStatDto,
} from './mock-notifications';
