/** Student Learning / Progress copy — no mock domain imports. */

export const studentCoursesPageCopy = {
  title: 'My Courses',
  description: 'Browse your enrollments, track progress, and continue where you left off.',
  searchLabel: 'Search courses',
  searchPlaceholder: 'Search by course or batch',
  statusFilterLabel: 'Filter by enrollment status',
  sortLabel: 'Sort courses',
  detailsButton: 'Details',
  continueButton: 'Continue learning',
  batchLabel: 'Batch',
  progressLabel: 'Progress',
  lessonsLabel: 'Lessons',
  completionLabel: 'Completion',
  enrolledLabel: 'Enrolled',
  lastProgressLabel: 'Last progress',
  emptyTitle: 'No courses yet',
  emptyDescription: 'When you enroll in a course, it will appear here.',
  noMatchesTitle: 'No matching courses',
  noMatchesDescription: 'Try a different search, status, or sort option.',
  errorTitle: 'Could not load courses',
  errorDescription: 'Check your connection and try again.',
  retryLabel: 'Retry',
  pageLabel: 'Page',
  previousLabel: 'Previous',
  nextLabel: 'Next',
  ofLabel: 'of',
} as const;

export const studentCourseDetailsCopy = {
  titleFallback: 'Course details',
  description: 'Review modules, lessons, and your progress for this enrollment.',
  batchLabel: 'Batch',
  progressLabel: 'Course progress',
  lessonsLabel: 'Lessons completed',
  continueButton: 'Continue learning',
  resumeButton: 'Resume lesson',
  teacherLabel: 'Teacher',
  teacherUnavailable: 'Teacher profile is not available from the Course API yet.',
  modulesLabel: 'Modules',
  moduleTitlesUnavailable: 'Module titles are not provided by the Lesson API.',
  emptyTitle: 'Course not found',
  emptyDescription: 'This enrollment may have been removed or is outside your scope.',
  errorTitle: 'Could not load course',
  errorDescription: 'Check your connection and try again.',
  retryLabel: 'Retry',
  backToCourses: 'Back to My Courses',
  statusLabel: 'Enrollment status',
  learningStatusLabel: 'Learning status',
} as const;

export const studentLessonPlayerCopy = {
  breadcrumbLearning: 'My Courses',
  previousLabel: 'Previous lesson',
  nextLabel: 'Next lesson',
  completeLabel: 'Mark complete',
  completingLabel: 'Saving…',
  completedLabel: 'Completed',
  progressLabel: 'Lesson progress',
  courseProgressLabel: 'Course progress',
  curriculumLabel: 'Course outline',
  resourcesLabel: 'Resources',
  notesLabel: 'Notes',
  resourcesUnavailable: 'Lesson resources are not available from the API yet.',
  notesUnavailable: 'Lesson notes are not available from the API yet.',
  contentUnavailable: 'This lesson has no playable content URL yet.',
  videoLabel: 'Video lesson',
  pdfLabel: 'PDF lesson',
  readingLabel: 'Reading lesson',
  exerciseLabel: 'Exercise lesson',
  otherLabel: 'Lesson content',
  openContent: 'Open content',
  completeError: 'Could not mark this lesson complete. Your previous progress was restored.',
  emptyTitle: 'Lesson not found',
  emptyDescription: 'This lesson may have been removed or is outside your enrollment.',
  errorTitle: 'Could not load lesson',
  errorDescription: 'Check your connection and try again.',
  retryLabel: 'Retry',
  sidebarToggle: 'Course outline',
  statusNotStarted: 'Not started',
  statusInProgress: 'In progress',
  statusCompleted: 'Completed',
} as const;

export const studentProgressPageCopy = {
  title: 'My Progress',
  description:
    'Track overall completion, per-course progress, milestones, and unlocked certificates.',
  overallLabel: 'Overall completion',
  completedLessonsLabel: 'Completed lessons',
  remainingLessonsLabel: 'Remaining lessons',
  totalLessonsLabel: 'Total lessons',
  coursesLabel: 'Course progress',
  milestonesLabel: 'Milestones',
  milestonesHint: 'Milestones unlock from your overall completion percentage.',
  certificatesLabel: 'Certificates',
  certificatesEmpty: 'No issued certificates yet.',
  certificatesHint: 'Only issued certificate records from the Certificate API are shown.',
  emptyTitle: 'No progress yet',
  emptyDescription: 'Start a lesson in one of your courses to build progress here.',
  errorTitle: 'Could not load progress',
  errorDescription: 'Check your connection and try again.',
  retryLabel: 'Retry',
  noDataPercent: 'Not available',
  unlocked: 'Unlocked',
  locked: 'Locked',
} as const;

export const studentEnrollmentStatusLabel = {
  active: 'Active',
  completed: 'Completed',
  inactive: 'Inactive',
} as const;

export const studentLearningStatusLabel = {
  not_started: 'Not started',
  in_progress: 'In progress',
  completed: 'Completed',
} as const;
