export const studentSettingsCopy = {
  title: 'Settings',
  description: 'Client-only preferences for your student workspace on this device.',
  loadingLabel: 'Loading settings…',
  errorTitle: 'Unable to load settings',
  errorDescription: 'Sign in again to manage your student preferences.',
  emptyTitle: 'Settings unavailable',
  emptyDescription: 'Sign in to manage client preferences.',
  clientOnlyBadge: 'Client-only',
  clientOnlyNote:
    'These preferences are saved in this browser only. Server preference sync is not integrated yet.',
  appearanceTitle: 'Appearance',
  appearanceDescription: 'Choose how the student portal looks on this device.',
  themeLabel: 'Theme',
  themeSystem: 'System',
  themeLight: 'Light',
  themeDark: 'Dark',
  languageTitle: 'Language',
  languageDescription: 'Preferred display language for this browser.',
  languageUnset: 'Not set',
  timezoneTitle: 'Timezone',
  timezoneDescription: 'Preferred timezone for this browser.',
  timezoneUnset: 'Not set',
  notificationsTitle: 'Notifications',
  notificationsDescription: 'In-app notification preference for this browser.',
  inAppNotifications: 'Show in-app notifications',
  privacyTitle: 'Privacy',
  privacyDescription: 'Visibility toggles stored on this device only.',
  showFullName: 'Show full name in discussions',
  allowMentorDm: 'Allow mentor direct messages',
  shareProgress: 'Share progress with organization',
  securityTitle: 'Security',
  securityDescription: 'Password and session management require server endpoints.',
  integrationsTitle: 'Integrations',
  integrationsDescription: 'External account connections are not integrated yet.',
  accountTitle: 'Account actions',
  accountDescription:
    'Account lifecycle actions stay disabled until real endpoints are available. Account deletion is not offered.',
  unavailableNote: 'Unavailable — not integrated',
  saveStatusSaved: 'Saved on this device',
} as const;
