export const studentPaymentsCopy = {
  title: 'Payments',
  description: 'Purchase courses, review payment history, invoices, and your subscription.',
  loadingLabel: 'Loading payments…',
  errorTitle: 'Unable to load payments',
  errorDescription: 'Something went wrong while loading payment data. Try again.',
  configUnsetTitle: 'Payments not configured',
  configUnsetDescription:
    'Checkout is unavailable until the payment provider is configured by your organization.',
  tabCatalog: 'Catalog',
  tabHistory: 'History',
  tabInvoices: 'Invoices',
  tabSubscription: 'Subscription',
  emptyCatalog: 'No purchasable courses or plans are available right now.',
  emptyHistory: 'No payment history yet.',
  emptyInvoices: 'No invoices yet.',
  emptySubscription: 'No active subscription.',
  purchaseCourse: 'Purchase',
  selectBatch: 'Select a batch',
  couponLabel: 'Coupon code',
  couponPlaceholder: 'Optional coupon',
  continueCheckout: 'Continue to checkout',
  orderSummary: 'Order summary',
  checkoutTitle: 'Complete purchase',
  verifying: 'Verifying payment…',
  cancelled: 'Checkout was cancelled. No charge was made.',
  failed: 'Payment failed. You can try again.',
  success: 'Payment verified successfully.',
  viewReceipt: 'View receipt',
  renew: 'Renew',
  upgrade: 'Upgrade',
  printReceipt: 'Print receipt',
} as const;
