export { TEACHER_COMING_SOON } from './copy';
export {
  teacherNavItems,
  teacherPageMeta,
  getTeacherPageMeta,
  type TeacherNavItem,
  type TeacherPageMeta,
} from './nav.config';
export {
  teacherDashboardCopy,
  type TeacherStatDto,
  type TeacherDashboardItemDto,
  type TeacherDashboardSectionDto,
  type TeacherDashboardDto,
} from './dashboard-types';
export {
  teacherCoursesPageCopy,
  teacherCourseStatusLabel,
  teacherCourseStatusFilterOptions,
  teacherCourseSortOptions,
  getTeacherCourseStats,
  formatTeacherCourseDate,
  toCourseListSort,
  toCourseApiStatus,
  type TeacherCourseStatus,
  type TeacherCoursesViewState,
  type TeacherCourseStatusFilter,
  type TeacherCourseSortOption,
  type TeacherCoursesViewMode,
  type TeacherCourseMediaDto,
  type TeacherCourseCountsDto,
  type TeacherCourseSummaryDto,
  type TeacherCourseStatDto,
} from './course-types';
export {
  teacherLessonsPageCopy,
  teacherLessonContentTypeLabel,
  teacherLessonContentTypeFilterOptions,
  teacherLessonSortOptions,
  getTeacherLessonStats,
  formatTeacherLessonDate,
  formatTeacherLessonDuration,
  getTeacherLessonById,
  toLessonListSort,
  toLessonApiContentType,
  type TeacherLessonContentType,
  type TeacherLessonsViewState,
  type TeacherLessonContentTypeFilter,
  type TeacherLessonSortOption,
  type TeacherLessonsViewMode,
  type TeacherLessonCourseRefDto,
  type TeacherLessonModuleRefDto,
  type TeacherLessonSummaryDto,
  type TeacherLessonStatDto,
} from './lesson-types';
export {
  teacherBatchesPageCopy,
  teacherBatchStatusLabel,
  teacherBatchStatusFilterOptions,
  teacherBatchSortOptions,
  getTeacherBatchStats,
  formatTeacherBatchDate,
  formatTeacherBatchDateTime,
  toBatchListSort,
  toBatchApiStatus,
  type TeacherBatchStatus,
  type TeacherBatchesViewState,
  type TeacherBatchStatusFilter,
  type TeacherBatchSortOption,
  type TeacherBatchesViewMode,
  type TeacherBatchMentorDto,
  type TeacherBatchCourseRefDto,
  type TeacherBatchProgressDto,
  type TeacherBatchLiveClassDto,
  type TeacherBatchSummaryDto,
  type TeacherBatchStatDto,
} from './batch-types';
export {
  teacherStudentsPageCopy,
  teacherStudentStatusLabel,
  teacherStudentStatusFilterOptions,
  teacherStudentSortOptions,
  getTeacherStudentStats,
  formatTeacherStudentDate,
  toEnrollmentListSort,
  toEnrollmentApiStatus,
  sortTeacherStudents,
  type TeacherStudentEnrollmentStatus,
  type TeacherStudentsViewState,
  type TeacherStudentStatusFilter,
  type TeacherStudentSortOption,
  type TeacherStudentsViewMode,
  type TeacherStudentBatchRefDto,
  type TeacherStudentCourseRefDto,
  type TeacherStudentProgressDto,
  type TeacherStudentSummaryDto,
  type TeacherStudentStatDto,
} from './student-types';
export {
  teacherAttendancePageCopy,
  attendanceSessionStatusLabel,
  attendanceStudentStatusLabel,
  attendanceStatusFilterOptions,
  attendanceSortOptions,
  getTeacherAttendanceStats,
  filterAttendanceSessions,
  sortAttendanceSessions,
  getAttendanceSessionById,
  formatAttendanceDate,
  formatAttendanceDateTime,
  toAttendanceListSort,
  toAttendanceApiMarkStatus,
  type AttendanceSessionStatus,
  type AttendanceStudentStatus,
  type TeacherAttendanceViewState,
  type AttendanceStatusFilter,
  type AttendanceSortOption,
  type TeacherAttendanceViewMode,
  type AttendanceCourseRefDto,
  type AttendanceBatchRefDto,
  type AttendanceMentorDto,
  type AttendanceRecordDto,
  type AttendanceCountsDto,
  type AttendanceSessionDto,
  type TeacherAttendanceStatDto,
} from './attendance-types';
export {
  teacherLiveClassesPageCopy,
  teacherLiveClassStatusLabel,
  teacherMeetingStatusLabel,
  teacherLiveClassStatusFilterOptions,
  teacherLiveClassProviderFilterOptions,
  teacherLiveClassSortOptions,
  getTeacherLiveClassStats,
  filterTeacherLiveClasses,
  sortTeacherLiveClasses,
  getTeacherLiveClassById,
  formatTeacherLiveClassDateTime,
  toLiveSessionListSort,
  toLiveSessionApiStatus,
  toLiveSessionApiProvider,
  type TeacherLiveClassStatus,
  type TeacherMeetingProvider,
  type TeacherMeetingStatus,
  type TeacherLiveClassesViewState,
  type TeacherLiveClassStatusFilter,
  type TeacherLiveClassSortOption,
  type TeacherLiveClassesViewMode,
  type TeacherLiveClassProviderFilter,
  type TeacherIntegrationAvailability,
  type TeacherLiveClassCourseRefDto,
  type TeacherLiveClassBatchRefDto,
  type TeacherLiveClassMentorDto,
  type TeacherLiveClassMeetingDto,
  type TeacherLiveClassAttendanceSummaryDto,
  type TeacherLiveClassIntegrationsDto,
  type TeacherLiveClassDto,
  type TeacherLiveClassStatDto,
} from './live-session-types';
export {
  teacherAssignmentsPageCopy,
  teacherAssignmentStatusLabel,
  teacherAssignmentStatusFilterOptions,
  teacherAssignmentSortOptions,
  getTeacherAssignmentStats,
  filterTeacherAssignments,
  sortTeacherAssignments,
  getTeacherAssignmentById,
  formatTeacherAssignmentDate,
  formatTeacherAssignmentDateTime,
  toAssignmentListSort,
  toAssignmentApiStatus,
  type TeacherAssignmentStatus,
  type TeacherAssignmentsViewState,
  type TeacherAssignmentStatusFilter,
  type TeacherAssignmentSortOption,
  type TeacherAssignmentsViewMode,
  type TeacherAssignmentCourseRefDto,
  type TeacherAssignmentBatchRefDto,
  type TeacherAssignmentAttachmentDto,
  type TeacherAssignmentSubmissionSummaryDto,
  type TeacherAssignmentGradingSummaryDto,
  type TeacherAssignmentTimelineEventDto,
  type TeacherAssignmentIntegrationsDto,
  type TeacherAssignmentDto,
  type TeacherAssignmentSummaryDto,
  type TeacherAssignmentStatDto,
} from './assignment-types';
export {
  teacherSubmissionsPageCopy,
  teacherSubmissionStatusLabel,
  teacherSubmissionStatusFilterOptions,
  teacherSubmissionSortOptions,
  getTeacherSubmissionStats,
  filterTeacherSubmissions,
  sortTeacherSubmissions,
  getTeacherSubmissionById,
  formatTeacherSubmissionDate,
  formatTeacherSubmissionDateTime,
  toSubmissionListSort,
  toSubmissionApiStatus,
  type TeacherSubmissionStatus,
  type TeacherSubmissionsViewState,
  type TeacherSubmissionStatusFilter,
  type TeacherSubmissionSortOption,
  type TeacherSubmissionsViewMode,
  type TeacherSubmissionAssignmentRefDto,
  type TeacherSubmissionStudentRefDto,
  type TeacherSubmissionAttachmentDto,
  type TeacherSubmissionGraderRefDto,
  type TeacherSubmissionSummaryDto,
  type TeacherSubmissionStatDto,
} from './submission-types';
export {
  teacherAnalyticsPageCopy,
  teacherAnalyticsChartTypeLabel,
  teacherAnalyticsTimeRangeOptions,
  buildTeacherAnalyticsOverview,
  getTeacherAnalyticsMetricById,
  getTeacherAnalyticsCourseById,
  filterTeacherAnalyticsSections,
  filterTeacherAnalyticsKpis,
  isTeacherAnalyticsTimeRange,
  type TeacherAnalyticsViewState,
  type TeacherAnalyticsTimeRange,
  type TeacherAnalyticsChartType,
  type TeacherAnalyticsMetricKind,
  type TeacherAnalyticsCourseRefDto,
  type TeacherAnalyticsMetricDto,
  type TeacherAnalyticsSectionDto,
  type TeacherAnalyticsOverviewDto,
  type TeacherAnalyticsSourceDto,
} from './analytics-types';
export {
  teacherMessagesPageCopy,
  teacherConversationTypeLabel,
  teacherMessageStatusLabel,
  teacherMessageFilterOptions,
  teacherMessageComingSoonFeatures,
  filterTeacherConversations,
  getTeacherConversationById,
  formatTeacherMessageDateTime,
  toConversationApiType,
  toConversationListSort,
  type TeacherConversationType,
  type TeacherMessageStatus,
  type TeacherMessagesViewState,
  type TeacherMessageFilter,
  type TeacherMessageIntegrationAvailability,
  type TeacherParticipantDto,
  type TeacherAttachmentDto,
  type TeacherMessageDto,
  type TeacherConversationFutureFeaturesDto,
  type TeacherConversationDto,
} from './message-types';
export {
  teacherCalendarComingSoonFeatures,
  teacherCalendarPageCopy,
  teacherCalendarEventTypeLabel,
  teacherCalendarEventStatusLabel,
  teacherCalendarEventFilterOptions,
  getTeacherCalendarInitialMonth,
  getTeacherCalendarTodayKey,
  getTeacherCalendarMonthRange,
  toCalendarListSort,
  buildTeacherCalendarMonth,
  filterTeacherCalendarEvents,
  getTeacherCalendarEventsForDay,
  getTeacherCalendarEventById,
  shiftTeacherCalendarMonth,
  formatTeacherCalendarDate,
  formatTeacherCalendarDateTime,
  getTeacherCalendarDateKey,
  type TeacherCalendarEventType,
  type TeacherCalendarEventStatus,
  type TeacherCalendarViewState,
  type TeacherCalendarEventFilter,
  type TeacherCalendarCourseRefDto,
  type TeacherCalendarBatchRefDto,
  type TeacherCalendarMentorDto,
  type TeacherCalendarFutureFeaturesDto,
  type TeacherCalendarEventDto,
  type TeacherCalendarDayDto,
  type TeacherCalendarMonthDto,
} from './calendar-types';
export {
  teacherNotificationFutureFeatures,
  teacherNotificationsPageCopy,
  teacherNotificationTypeLabel,
  teacherNotificationPriorityLabel,
  teacherNotificationStatusFilterOptions,
  teacherNotificationSortOptions,
  getTeacherNotificationStats,
  filterTeacherNotifications,
  sortTeacherNotifications,
  getTeacherNotificationById,
  isTeacherNotificationUnread,
  formatTeacherNotificationDate,
  formatTeacherNotificationRelativeTime,
  toNotificationApiType,
  toNotificationApiUnreadOnly,
  toNotificationListSort,
  type TeacherNotificationsViewState,
  type TeacherNotificationType,
  type TeacherNotificationPriority,
  type TeacherNotificationStatusFilter,
  type TeacherNotificationSortOption,
  type TeacherNotificationFutureFeaturesDto,
  type TeacherNotificationDto,
  type TeacherNotificationStatDto,
} from './notification-types';
export {
  teacherCertificatesPageCopy,
  teacherCertificateStatusLabel,
  teacherCertificateStatusFilterOptions,
  teacherCertificateSortOptions,
  teacherCertificateComingSoonFeatures,
  getTeacherCertificateStats,
  filterTeacherCertificates,
  sortTeacherCertificates,
  getTeacherCertificateById,
  deriveTeacherCertificateBatches,
  deriveTeacherCertificateTemplates,
  formatTeacherCertificateDate,
  formatTeacherCertificateDateTime,
  toCertificateListSort,
  toCertificateApiStatus,
  type StudentCertificateStatus,
  type TeacherCertificatesViewState,
  type TeacherCertificateStatusFilter,
  type TeacherCertificateSortOption,
  type TeacherCertificateStudentRefDto,
  type TeacherCertificateCourseRefDto,
  type TeacherCertificateBatchRefDto,
  type TeacherCertificateMentorDto,
  type TeacherCertificateFutureFeaturesDto,
  type StudentCertificateDto,
  type TeacherCertificateSummaryDto,
  type CertificateTemplateDto,
  type CertificateBatchDto,
  type TeacherCertificateStatDto,
} from './certificate-types';
export {
  teacherProfileViewState,
  teacherSettingsViewState,
  teacherProfilePageCopy,
  teacherSettingsPageCopy,
  teacherThemePreferenceLabel,
  teacherProfileDefaults,
  buildTeacherProfileFromAuth,
  getTeacherDisplayName,
  formatTeacherProfileDate,
  getTeacherLanguageLabel,
  type TeacherProfileViewState,
  type TeacherSettingsViewState,
  type TeacherThemePreference,
  type TeacherNotificationPreferencesDto,
  type TeacherConnectedAccountDto,
  type TeacherPreferencesDto,
  type TeacherProfileFutureFeaturesDto,
  type TeacherProfileDto,
} from './mock-teacher-profile';
