export {
  teacherNavItems,
  teacherPageMeta,
  getTeacherPageMeta,
  type TeacherNavItem,
  type TeacherPageMeta,
} from './nav.config';
export {
  teacherProfilePlaceholder,
  teacherGreetingPlaceholder,
  teacherStatsPlaceholder,
  teacherTodaysClassesPlaceholder,
  teacherRecentActivityPlaceholder,
  teacherUpcomingWorkPlaceholder,
  teacherDashboardSections,
  teacherNotificationPlaceholders,
  teacherDashboardViewState,
  type TeacherViewState,
  type TeacherProfilePlaceholderDto,
  type TeacherGreetingDto,
  type TeacherStatDto,
  type TeacherPlaceholderItemDto,
  type TeacherSectionPlaceholderDto,
  type TeacherNotificationPlaceholderDto,
} from './dashboard-placeholder';
export {
  teacherCoursesViewState,
  teacherCoursesPageCopy,
  teacherCourseStatusLabel,
  teacherCourseStatusFilterOptions,
  teacherCourseSortOptions,
  teacherCourses,
  getTeacherCourseStats,
  filterTeacherCourses,
  sortTeacherCourses,
  formatTeacherCourseDate,
  type TeacherCourseStatus,
  type TeacherCoursesViewState,
  type TeacherCourseStatusFilter,
  type TeacherCourseSortOption,
  type TeacherCoursesViewMode,
  type TeacherCourseMediaDto,
  type TeacherCourseCountsDto,
  type TeacherCourseSummaryDto,
  type TeacherCourseStatDto,
} from './mock-courses';
export {
  teacherBatchesViewState,
  teacherBatchesPageCopy,
  teacherBatchStatusLabel,
  teacherBatchStatusFilterOptions,
  teacherBatchSortOptions,
  teacherBatches,
  getTeacherBatchStats,
  filterTeacherBatches,
  sortTeacherBatches,
  formatTeacherBatchDate,
  formatTeacherBatchDateTime,
  type TeacherBatchStatus,
  type TeacherBatchesViewState,
  type TeacherBatchStatusFilter,
  type TeacherBatchSortOption,
  type TeacherBatchesViewMode,
  type TeacherBatchMentorDto,
  type TeacherBatchCourseRefDto,
  type TeacherBatchProgressDto,
  type TeacherBatchLiveClassDto,
  type TeacherBatchSummaryDto,
  type TeacherBatchStatDto,
} from './mock-batches';
export {
  teacherStudentsViewState,
  teacherStudentsPageCopy,
  teacherStudentStatusLabel,
  teacherStudentStatusFilterOptions,
  teacherStudentSortOptions,
  teacherStudents,
  getTeacherStudentStats,
  filterTeacherStudents,
  sortTeacherStudents,
  formatTeacherStudentDate,
  type TeacherStudentEnrollmentStatus,
  type TeacherStudentsViewState,
  type TeacherStudentStatusFilter,
  type TeacherStudentSortOption,
  type TeacherStudentsViewMode,
  type TeacherStudentBatchRefDto,
  type TeacherStudentCourseRefDto,
  type TeacherStudentProgressDto,
  type TeacherStudentSummaryDto,
  type TeacherStudentStatDto,
} from './mock-students';
export {
  teacherAttendanceViewState,
  teacherAttendancePageCopy,
  attendanceSessionStatusLabel,
  attendanceStudentStatusLabel,
  attendanceStatusFilterOptions,
  attendanceSortOptions,
  attendanceSessions,
  getTeacherAttendanceStats,
  filterAttendanceSessions,
  sortAttendanceSessions,
  getAttendanceSessionById,
  formatAttendanceDate,
  formatAttendanceDateTime,
  type AttendanceSessionStatus,
  type AttendanceStudentStatus,
  type TeacherAttendanceViewState,
  type AttendanceStatusFilter,
  type AttendanceSortOption,
  type TeacherAttendanceViewMode,
  type AttendanceCourseRefDto,
  type AttendanceBatchRefDto,
  type AttendanceMentorDto,
  type AttendanceRecordDto,
  type AttendanceCountsDto,
  type AttendanceSessionDto,
  type TeacherAttendanceStatDto,
} from './mock-attendance';
export {
  teacherLiveClassesViewState,
  teacherLiveClassesPageCopy,
  teacherLiveClassStatusLabel,
  teacherMeetingStatusLabel,
  teacherLiveClassStatusFilterOptions,
  teacherLiveClassSortOptions,
  teacherLiveClasses,
  getTeacherLiveClassStats,
  filterTeacherLiveClasses,
  sortTeacherLiveClasses,
  getTeacherLiveClassById,
  formatTeacherLiveClassDateTime,
  type TeacherLiveClassStatus,
  type TeacherMeetingProvider,
  type TeacherMeetingStatus,
  type TeacherLiveClassesViewState,
  type TeacherLiveClassStatusFilter,
  type TeacherLiveClassSortOption,
  type TeacherLiveClassesViewMode,
  type TeacherIntegrationAvailability,
  type TeacherLiveClassCourseRefDto,
  type TeacherLiveClassBatchRefDto,
  type TeacherLiveClassMentorDto,
  type TeacherLiveClassMeetingDto,
  type TeacherLiveClassAttendanceSummaryDto,
  type TeacherLiveClassIntegrationsDto,
  type TeacherLiveClassDto,
  type TeacherLiveClassStatDto,
} from './mock-live-classes';
export {
  teacherAssignmentsViewState,
  teacherAssignmentsPageCopy,
  teacherAssignmentStatusLabel,
  teacherAssignmentStatusFilterOptions,
  teacherAssignmentSortOptions,
  teacherAssignments,
  getTeacherAssignmentStats,
  filterTeacherAssignments,
  sortTeacherAssignments,
  getTeacherAssignmentById,
  formatTeacherAssignmentDate,
  formatTeacherAssignmentDateTime,
  type TeacherAssignmentStatus,
  type TeacherAssignmentsViewState,
  type TeacherAssignmentStatusFilter,
  type TeacherAssignmentSortOption,
  type TeacherAssignmentsViewMode,
  type TeacherAssignmentCourseRefDto,
  type TeacherAssignmentBatchRefDto,
  type TeacherAssignmentAttachmentDto,
  type TeacherAssignmentSubmissionSummaryDto,
  type TeacherAssignmentGradingSummaryDto,
  type TeacherAssignmentTimelineEventDto,
  type TeacherAssignmentIntegrationsDto,
  type TeacherAssignmentDto,
  type TeacherAssignmentStatDto,
} from './mock-assignments';
export {
  teacherAnalyticsViewState,
  teacherAnalyticsPageCopy,
  teacherAnalyticsChartTypeLabel,
  teacherAnalyticsTimeRangeOptions,
  teacherAnalyticsCourses,
  teacherAnalyticsMetrics,
  teacherAnalyticsKpis,
  teacherAnalyticsSections,
  teacherAnalyticsOverview,
  getTeacherAnalyticsMetricById,
  getTeacherAnalyticsCourseById,
  filterTeacherAnalyticsSections,
  filterTeacherAnalyticsKpis,
  isTeacherAnalyticsTimeRange,
  type TeacherAnalyticsViewState,
  type TeacherAnalyticsTimeRange,
  type TeacherAnalyticsChartType,
  type TeacherAnalyticsMetricKind,
  type TeacherAnalyticsCourseRefDto,
  type TeacherAnalyticsMetricDto,
  type TeacherAnalyticsSectionDto,
  type TeacherAnalyticsOverviewDto,
} from './mock-analytics';
export {
  teacherMessagesViewState,
  teacherMessagesPageCopy,
  teacherConversationTypeLabel,
  teacherMessageStatusLabel,
  teacherMessageFilterOptions,
  teacherConversations,
  filterTeacherConversations,
  getTeacherConversationById,
  formatTeacherMessageDateTime,
  type TeacherConversationType,
  type TeacherMessageStatus,
  type TeacherMessagesViewState,
  type TeacherMessageFilter,
  type TeacherParticipantDto,
  type TeacherAttachmentDto,
  type TeacherMessageDto,
  type TeacherConversationFutureFeaturesDto,
  type TeacherConversationDto,
} from './mock-messages';
export {
  teacherCalendarViewState,
  teacherCalendarPageCopy,
  teacherCalendarEventTypeLabel,
  teacherCalendarEventStatusLabel,
  teacherCalendarEventFilterOptions,
  teacherCalendarInitialMonth,
  teacherCalendarEvents,
  buildTeacherCalendarMonth,
  filterTeacherCalendarEvents,
  getTeacherCalendarEventsForDay,
  getTeacherCalendarEventById,
  shiftTeacherCalendarMonth,
  formatTeacherCalendarDate,
  formatTeacherCalendarDateTime,
  getTeacherCalendarDateKey,
  type TeacherCalendarEventType,
  type TeacherCalendarEventStatus,
  type TeacherCalendarViewState,
  type TeacherCalendarEventFilter,
  type TeacherCalendarCourseRefDto,
  type TeacherCalendarBatchRefDto,
  type TeacherCalendarMentorDto,
  type TeacherCalendarFutureFeaturesDto,
  type TeacherCalendarEventDto,
  type TeacherCalendarDayDto,
  type TeacherCalendarMonthDto,
} from './mock-calendar';
