import {
  Award,
  Bell,
  BookOpen,
  Calendar,
  Check,
  ChevronDown,
  ClipboardList,
  Clock,
  Compass,
  CreditCard,
  Eye,
  Globe,
  GraduationCap,
  LayoutDashboard,
  Lightbulb,
  LogOut,
  Mail,
  MapPin,
  Menu,
  MessageCircle,
  Moon,
  PanelLeftClose,
  PanelLeftOpen,
  PenTool,
  Phone,
  PlayCircle,
  Search,
  Settings,
  Share2,
  Sun,
  Target,
  TrendingUp,
  User,
  Users,
  Video,
  X,
  type LucideIcon,
} from 'lucide-react';

/**
 * Central icon map — import icons from here instead of lucide-react in feature code.
 */
export const icons = {
  menu: Menu,
  close: X,
  check: Check,
  chevronDown: ChevronDown,
  globe: Globe,
  mail: Mail,
  share: Share2,
  video: Video,
  phone: Phone,
  mapPin: MapPin,
  clock: Clock,
  message: MessageCircle,
  eye: Eye,
  users: Users,
  user: User,
  compass: Compass,
  graduation: GraduationCap,
  search: Search,
  lightbulb: Lightbulb,
  pen: PenTool,
  book: BookOpen,
  target: Target,
  trending: TrendingUp,
  clipboard: ClipboardList,
  award: Award,
  dashboard: LayoutDashboard,
  calendar: Calendar,
  creditCard: CreditCard,
  settings: Settings,
  logout: LogOut,
  bell: Bell,
  sun: Sun,
  moon: Moon,
  panelClose: PanelLeftClose,
  panelOpen: PanelLeftOpen,
  play: PlayCircle,
} as const satisfies Record<string, LucideIcon>;

export type IconName = keyof typeof icons;

export function getIcon(name: IconName): LucideIcon {
  return icons[name];
}
