export const studentLivePageCopy = {
  title: 'Live Classes',
  description:
    'Join your batch live sessions, review attendance marks, and open recordings when available.',
  searchPlaceholder: 'Search sessions, courses, or batches',
  searchLabel: 'Search live classes',
  statusFilterLabel: 'Filter by session status',
  scheduleFilterLabel: 'Filter by schedule',
  courseFilterLabel: 'Filter by course',
  batchFilterLabel: 'Filter by batch',
  sortLabel: 'Sort live classes',
  collectionLabel: 'Your live classes',
  emptyTitle: 'No live classes yet',
  emptyDescription: 'Live sessions for your enrolled batches will appear here.',
  noMatchesTitle: 'No matching live classes',
  noMatchesDescription: 'Try a different search, schedule, or status filter.',
  errorTitle: 'Unable to load live classes',
  errorDescription: 'Something went wrong while loading Live Classes. Please try again.',
  joinButton: 'Join class',
  recordingButton: 'Watch recording',
  calendarButton: 'Add to calendar',
  detailsButton: 'View details',
  detailsCloseLabel: 'Close session details',
  attendanceLabel: 'Your attendance',
  notMarkedLabel: 'Not marked',
  meetingUrlPending: 'Meeting link unavailable',
  recordingUnavailable: 'Recording unavailable',
  paginationLabel: 'Live class pages',
} as const;

export const studentAssignmentsPageCopy = {
  title: 'Assignments',
  description: 'Review published work, submit written responses, and read grades or feedback.',
  searchPlaceholder: 'Search assignments or courses',
  searchLabel: 'Search assignments',
  statusFilterLabel: 'Filter by assignment status',
  courseFilterLabel: 'Filter by course',
  batchFilterLabel: 'Filter by batch',
  sortLabel: 'Sort assignments',
  collectionLabel: 'Your assignments',
  emptyTitle: 'No assignments yet',
  emptyDescription: 'Published assignments for your courses will appear here.',
  noMatchesTitle: 'No matching assignments',
  noMatchesDescription: 'Try a different search or status filter.',
  errorTitle: 'Unable to load assignments',
  errorDescription: 'Something went wrong while loading Assignments. Please try again.',
  detailsButton: 'Open assignment',
  detailsCloseLabel: 'Close assignment details',
  submitButton: 'Submit',
  updateButton: 'Update submission',
  savingLabel: 'Saving…',
  savedLabel: 'Saved',
  retryLabel: 'Retry save',
  attachmentsDisabled: 'File attachments are unavailable until storage support is ready.',
  noSubmissionLabel: 'Not submitted',
  instructionsLabel: 'Instructions',
  gradeLabel: 'Grade',
  feedbackLabel: 'Feedback',
  contentLabel: 'Your written response',
  paginationLabel: 'Assignment pages',
} as const;

export const studentAttendancePageCopy = {
  title: 'Attendance',
  description: 'Your attendance history across live sessions, with an honest completion rate.',
  searchPlaceholder: 'Search sessions, courses, or batches',
  searchLabel: 'Search attendance',
  statusFilterLabel: 'Filter by attendance status',
  courseFilterLabel: 'Filter by course',
  batchFilterLabel: 'Filter by batch',
  sessionFilterLabel: 'Filter by live session',
  sortLabel: 'Sort attendance',
  collectionLabel: 'Your attendance records',
  emptyTitle: 'No attendance records yet',
  emptyDescription: 'Attendance marks from your live sessions will appear here.',
  noMatchesTitle: 'No matching attendance records',
  noMatchesDescription: 'Try a different search, status, course, or session filter.',
  errorTitle: 'Unable to load attendance',
  errorDescription: 'Something went wrong while loading Attendance. Please try again.',
  rateLabel: 'Attendance rate',
  rateUnavailable: 'Not enough records',
  paginationLabel: 'Attendance pages',
} as const;

export const studentCertificatesPageCopy = {
  title: 'Certificates',
  description:
    'View certificates issued to you, verify authenticity, and download PDFs when available.',
  searchPlaceholder: 'Search courses, batches, or certificate numbers',
  searchLabel: 'Search certificates',
  statusFilterLabel: 'Filter by certificate status',
  courseFilterLabel: 'Filter by course',
  sortLabel: 'Sort certificates',
  collectionLabel: 'Your certificates',
  emptyTitle: 'No certificates yet',
  emptyDescription: 'Certificates earned for your courses will appear here.',
  noMatchesTitle: 'No matching certificates',
  noMatchesDescription: 'Try a different search, status, or course filter.',
  errorTitle: 'Unable to load certificates',
  errorDescription: 'Something went wrong while loading Certificates. Please try again.',
  detailsButton: 'View details',
  detailsCloseLabel: 'Close certificate details',
  downloadButton: 'Download PDF',
  verifyButton: 'Verify certificate',
  verifyingLabel: 'Verifying…',
  verifySuccess: 'Certificate verified',
  verifyFailure: 'Verification failed. Check the code and try again.',
  verificationCodeLabel: 'Verification code',
  qrUnavailable: 'QR code unavailable until generation is supported.',
  downloadUnavailable: 'PDF download unavailable until a file URL exists.',
  paginationLabel: 'Certificate pages',
} as const;

export const studentAttendanceStatusLabel: Record<
  'present' | 'absent' | 'late' | 'excused',
  string
> = {
  present: 'Present',
  absent: 'Absent',
  late: 'Late',
  excused: 'Excused',
};
