export const studentHomeCopy = {
  portalLabel: 'Student Portal',
  welcomeFallback: 'Welcome back',
  welcomeNamed: (name: string) => `Welcome back, ${name}`,
  welcomeDescription: 'Your classes, courses, and work for today — loaded from your account.',
  loadingLabel: 'Loading your dashboard…',
  errorTitle: 'Unable to load your dashboard',
  errorDescription: 'Something went wrong while loading your learning data. Try again.',
  retryButton: 'Retry',
  statsAriaLabel: 'Learning statistics',
  missingValue: '—',
  overallProgressTitle: 'Overall progress',
  overallProgressDescription: 'Derived from lesson completion across your active courses.',
  overallProgressEmpty: 'No lesson progress on active courses yet',
  coursesTitle: 'Current courses',
  coursesDescription: 'Active enrollments still in progress.',
  coursesEmpty: 'No active courses right now',
  assignmentsTitle: 'Assignments due',
  assignmentsDescription: 'Published work still awaiting your submission.',
  assignmentsEmpty: 'No assignments due',
  certificatesTitle: 'Certificates',
  certificatesDescription: 'Issued and recorded certificates in your account.',
  certificatesEmpty: 'No certificates issued yet',
  notificationsTitle: 'Notifications',
  notificationsDescription: 'Recent in-app notifications for your account.',
  notificationsEmpty: 'No notifications yet',
  unreadLabel: (count: number) => `${String(count)} unread`,
  recentActivityTitle: 'Recent activity',
  recentActivityDescription: 'Latest notification activity from your account.',
  recentActivityEmpty: 'No recent activity',
  calendarTitle: 'Calendar preview',
  calendarDescription: 'Upcoming calendar events from your organization.',
  calendarEmpty: 'No upcoming calendar events',
  quickLinksTitle: 'Quick links',
  quickLinksDescription: 'Jump to common student workspace areas.',
  continueCourse: 'Continue',
  viewCourse: 'Open course',
  lessonsProgress: (completed: number, total: number) =>
    `${String(completed)} / ${String(total)} lessons`,
  duePrefix: 'Due',
  issuedPrefix: 'Issued',
  capabilityTitle: 'Unavailable integrations',
  capabilityDescription:
    'Email delivery, media upload, Zoom OAuth, calendar sync, PDF, and QR features are not integrated yet.',
} as const;
