export const studentProfileCopy = {
  title: 'Profile',
  description: 'Your account identity, organization membership, and learning summary.',
  loadingLabel: 'Loading profile…',
  errorTitle: 'Unable to load your profile',
  errorDescription: 'Something went wrong while loading your profile. Try again.',
  retryButton: 'Retry',
  emptyTitle: 'Profile unavailable',
  emptyDescription: 'Sign in to view your student profile.',
  summaryLabel: 'Profile summary',
  avatarAlt: 'Profile avatar placeholder',
  roleLabel: 'Role',
  editProfile: 'Edit profile',
  uploadAvatar: 'Upload avatar',
  unavailableNote: 'This action is not integrated yet.',
  personalTitle: 'Personal identity',
  firstNameLabel: 'First name',
  lastNameLabel: 'Last name',
  emailLabel: 'Email',
  phoneLabel: 'Phone',
  statusLabel: 'Account status',
  emailVerifiedLabel: 'Email verified',
  rolesLabel: 'Roles',
  missingValue: '—',
  activeStatus: 'Active',
  inactiveStatus: 'Inactive',
  verifiedYes: 'Verified',
  verifiedNo: 'Not verified',
  organizationTitle: 'Organization membership',
  organizationDescription:
    'Organization IDs from your authenticated session. Organization details are not loaded here.',
  organizationEmpty: 'No organization memberships on this account.',
  organizationIdLabel: 'Organization ID',
  learningTitle: 'Learning stats',
  learningDescription: 'Derived from your lesson progress and certificate records.',
  learningEmpty: 'No learning progress available yet.',
  completedLessons: 'Completed lessons',
  totalLessons: 'Total lessons',
  progressPercent: 'Overall progress',
  remainingLessons: 'Remaining lessons',
  certificatesUnlocked: 'Certificates unlocked',
  certificatesTitle: 'Issued certificates',
  certificatesDescription: 'Certificates returned for your account.',
  certificatesEmpty: 'No certificates issued yet.',
  preferencesTitle: 'Preferences',
  preferencesDescription:
    'Client-only preferences stored in this browser. They are not synced to the server yet.',
  themeLabel: 'Theme',
  languageLabel: 'Language',
  timezoneLabel: 'Timezone',
} as const;
